repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: '96221dc741cb30cc0136999083dc6bd0e2113000'
    hooks:
      - id: go-fmt
      - id: go-build
      - id: go-mod-tidy
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '9daf4ccb1f73e83c75517076bc2c1aafde20a082'
    hooks:
      - id: shellcheck
